cc_library(
    name = "data_target",
    srcs = [
        "DatabaseWrapper.cpp",
        "Preprocessor.cpp",
    ],
    deps = [
        "//src/include/modules:modules_headers",
    ],
    includes = [
        "include",
    ],
    visibility = ["//visibility:public"],
)