cc_library(
    name = "data_target",
    srcs = [
        "DatabaseWrapper.cpp",
        "Preprocessor.cpp",
    ],
    hdrs = [
        "DatabaseWrapper.h",
        "Preprocessor.h",
        "TimeSeries.h",
    ],
    visibility = ["//visibility:public"],
)